# █░█ █▄█ █▀█ █▀█ █░░ ▄▀█ █▄░█ █▀▄
# █▀█ ░█░ █▀▀ █▀▄ █▄▄ █▀█ █░▀█ █▄▀

# Monitor
monitor=,preferred,auto,1

# Variables
$mod = SUPER
$terminal = kitty
$menu = wofi --show drun
$filemanager = thunar
$browser = firefox

# Autostart
exec-once = waybar
exec-once = dunst
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = swww-daemon

# Environment
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt6ct

# Input
input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0
    touchpad {
        natural_scroll = true
        tap-to-click = true
    }
}

# General
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(c084fcff) rgba(f472b6ff) 45deg
    col.inactive_border = rgba(1e1e2eaa)
    layout = dwindle
    resize_on_border = true
}

# Decoration
decoration {
    rounding = 12
    active_opacity = 1.0
    inactive_opacity = 0.9
    blur {
        enabled = true
        size = 6
        passes = 3
        new_optimizations = true
    }
shadow{
    enabled = true
    range = 15
    color = rgba(0,0,0,0.4)
      }
}

# Animations
animations {
    enabled = true
    bezier = smooth, 0.05, 0.9, 0.1, 1.05
    bezier = linear, 0.0, 0.0, 1.0, 1.0
    animation = windows, 1, 6, smooth, slide
    animation = windowsOut, 1, 5, smooth, popin 80%
    animation = fade, 1, 6, smooth
    animation = workspaces, 1, 5, smooth, slidevert
}

# Layout
dwindle {
    preserve_split = true
}

# Misc
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
}

# ─── KEYBINDS ───────────────────────────────

# Apps
bind = $mod, T, exec, $terminal
bind = $mod, E, exec, $filemanager
bind = $mod, B, exec, $browser
bind = $mod, Space, exec, $menu

# Window
bind = $mod, Q, killactive
bind = $mod, F, fullscreen
bind = $mod, V, togglefloating
bind = $mod, P, pseudo

# Focus
bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d

# Move windows
bind = $mod SHIFT, left, movewindow, l
bind = $mod SHIFT, right, movewindow, r
bind = $mod SHIFT, up, movewindow, u
bind = $mod SHIFT, down, movewindow, d

# Workspaces
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5

# Scroll workspaces
bind = $mod, mouse_down, workspace, e+1
bind = $mod, mouse_up, workspace, e-1

# Mouse
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# Screenshot
bind = , Print, exec, grimblast copy area
bind = $mod, Print, exec, grimblast copy screen

# Volume
bind = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# Brightness
bind = , XF86MonBrightnessUp, exec, brightnessctl set 5%+
bind = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

# Lock
bind = $mod, L, exec, hyprlock

# Exit
bind = $mod SHIFT, Q, exit
exec-once = swaybg -i /home/veer/Pictures/wallpapers/wallhaven-9o833w_1920x1080.png -m fill
